services:
  backend:
    build:
      context: ./backend
    command: /start_prod.sh
    environment:
      - DEBUG=False
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - django-static:/backend/staticfiles
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: serve -s dist
    volumes:
      - ./frontend:/app
    expose:
      - 3000
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - django-static:/static
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  django-static:
