# Generated by Django 5.0.6 on 2024-06-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('executors', models.CharField(blank=True, max_length=100, verbose_name='Список исполнителей')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(choices=[('Назначена', 'New'), ('Выполняется', 'In Progress'), ('Приостановлена', 'Paused'), ('Завершена', 'Done')], default='Назначена', max_length=100)),
                ('complexity', models.IntegerField(verbose_name='Сложность')),
                ('execution_time', models.DurationField(verbose_name='Время выполнения')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks_app.task')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
