# Generated by Django 5.0.6 on 2024-06-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=None, verbose_name='Дата завершения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='execution_time',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Время выполнения'),
        ),
    ]
