# Generated by Django 5.0.6 on 2024-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_alter_task_creation_date_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
    ]
